// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrucksProject.Infra.DataContext;

namespace TrucksProject.Infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211118020332_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrucksProject.Domain.Entities.ModelTruck", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("ModelTruck");

                    b.HasData(
                        new
                        {
                            Name = "FH"
                        },
                        new
                        {
                            Name = "FM"
                        });
                });

            modelBuilder.Entity("TrucksProject.Domain.Entities.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdModelTruck")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YearFabrication")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("YearModel")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdModelTruck");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("TrucksProject.Domain.Entities.Truck", b =>
                {
                    b.HasOne("TrucksProject.Domain.Entities.ModelTruck", "ModelTruck")
                        .WithMany("Trucks")
                        .HasForeignKey("IdModelTruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelTruck");
                });

            modelBuilder.Entity("TrucksProject.Domain.Entities.ModelTruck", b =>
                {
                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
